# ==========================================
# Configuration Apache JMeter
# Projet : CI-Lab
# ==========================================

# Version de JMeter
JMETER_VERSION="5.6.3"

# Compte applicatif
JMETER_USER="jmeterapp"

# Répertoire d'installation
JMETER_HOME="/opt/jmeter"

# Archive JMeter
JMETER_ARCHIVE="/opt/apache-jmeter-${JMETER_VERSION}.tgz"

# Répertoires de travail
JMETER_TESTS="${JMETER_HOME}/tests"
JMETER_RESULTS="${JMETER_HOME}/results"
JMETER_REPORTS="${JMETER_HOME}/reports"
